#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gedit-plugins-gnome
Version  : 3.38
Release  : 1
URL      : https://gitlab.gnome.org/GNOME/gedit-plugins/-/archive/gnome-3-38/gedit-plugins-gnome-3-38.tar.bz2
Source0  : https://gitlab.gnome.org/GNOME/gedit-plugins/-/archive/gnome-3-38/gedit-plugins-gnome-3-38.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: gedit-plugins-gnome-data = %{version}-%{release}
Requires: gedit-plugins-gnome-lib = %{version}-%{release}
Requires: gedit-plugins-gnome-license = %{version}-%{release}
Requires: gedit-plugins-gnome-locales = %{version}-%{release}
BuildRequires : appstream-glib
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : libpeas-dev
BuildRequires : pkgconfig(gedit)
BuildRequires : pkgconfig(libpeas-1.0)

%description
gedit-plugins
=============
This is version 3.38.1 of gedit-plugins.
gedit-plugins is a set of additional plugins for the
[gedit](https://wiki.gnome.org/Apps/Gedit) text editor.

%package data
Summary: data components for the gedit-plugins-gnome package.
Group: Data

%description data
data components for the gedit-plugins-gnome package.


%package doc
Summary: doc components for the gedit-plugins-gnome package.
Group: Documentation

%description doc
doc components for the gedit-plugins-gnome package.


%package lib
Summary: lib components for the gedit-plugins-gnome package.
Group: Libraries
Requires: gedit-plugins-gnome-data = %{version}-%{release}
Requires: gedit-plugins-gnome-license = %{version}-%{release}

%description lib
lib components for the gedit-plugins-gnome package.


%package license
Summary: license components for the gedit-plugins-gnome package.
Group: Default

%description license
license components for the gedit-plugins-gnome package.


%package locales
Summary: locales components for the gedit-plugins-gnome package.
Group: Default

%description locales
locales components for the gedit-plugins-gnome package.


%prep
%setup -q -n gedit-plugins-gnome-3-38
cd %{_builddir}/gedit-plugins-gnome-3-38

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1613407399
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/gedit-plugins-gnome
cp %{_builddir}/gedit-plugins-gnome-3-38/COPYING %{buildroot}/usr/share/package-licenses/gedit-plugins-gnome/68c94ffc34f8ad2d7bfae3f5a6b996409211c1b1
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang gedit-plugins

%files
%defattr(-,root,root,-)
/usr/lib64/gedit/plugins/bookmarks.plugin
/usr/lib64/gedit/plugins/bracketcompletion.plugin
/usr/lib64/gedit/plugins/bracketcompletion.py
/usr/lib64/gedit/plugins/charmap.plugin
/usr/lib64/gedit/plugins/charmap/__init__.py
/usr/lib64/gedit/plugins/charmap/panel.py
/usr/lib64/gedit/plugins/codecomment.plugin
/usr/lib64/gedit/plugins/codecomment.py
/usr/lib64/gedit/plugins/colorpicker.plugin
/usr/lib64/gedit/plugins/colorpicker.py
/usr/lib64/gedit/plugins/colorschemer.plugin
/usr/lib64/gedit/plugins/colorschemer/__init__.py
/usr/lib64/gedit/plugins/colorschemer/languages.py
/usr/lib64/gedit/plugins/colorschemer/schemer.py
/usr/lib64/gedit/plugins/commander.plugin
/usr/lib64/gedit/plugins/commander/__init__.py
/usr/lib64/gedit/plugins/commander/appactivatable.py
/usr/lib64/gedit/plugins/commander/commands/__init__.py
/usr/lib64/gedit/plugins/commander/commands/accel_group.py
/usr/lib64/gedit/plugins/commander/commands/completion.py
/usr/lib64/gedit/plugins/commander/commands/exceptions.py
/usr/lib64/gedit/plugins/commander/commands/metamodule.py
/usr/lib64/gedit/plugins/commander/commands/method.py
/usr/lib64/gedit/plugins/commander/commands/module.py
/usr/lib64/gedit/plugins/commander/commands/result.py
/usr/lib64/gedit/plugins/commander/commands/rollbackimporter.py
/usr/lib64/gedit/plugins/commander/entry.py
/usr/lib64/gedit/plugins/commander/history.py
/usr/lib64/gedit/plugins/commander/info.py
/usr/lib64/gedit/plugins/commander/modules.py
/usr/lib64/gedit/plugins/commander/utils.py
/usr/lib64/gedit/plugins/commander/windowactivatable.py
/usr/lib64/gedit/plugins/drawspaces.plugin
/usr/lib64/gedit/plugins/findinfiles.plugin
/usr/lib64/gedit/plugins/git.plugin
/usr/lib64/gedit/plugins/git/__init__.py
/usr/lib64/gedit/plugins/git/appactivatable.py
/usr/lib64/gedit/plugins/git/debug.py
/usr/lib64/gedit/plugins/git/diffrenderer.py
/usr/lib64/gedit/plugins/git/viewactivatable.py
/usr/lib64/gedit/plugins/git/windowactivatable.py
/usr/lib64/gedit/plugins/git/workerthread.py
/usr/lib64/gedit/plugins/gpdefs.py
/usr/lib64/gedit/plugins/joinlines.plugin
/usr/lib64/gedit/plugins/joinlines.py
/usr/lib64/gedit/plugins/multiedit.plugin
/usr/lib64/gedit/plugins/multiedit/__init__.py
/usr/lib64/gedit/plugins/multiedit/appactivatable.py
/usr/lib64/gedit/plugins/multiedit/signals.py
/usr/lib64/gedit/plugins/multiedit/viewactivatable.py
/usr/lib64/gedit/plugins/multiedit/windowactivatable.py
/usr/lib64/gedit/plugins/sessionsaver.plugin
/usr/lib64/gedit/plugins/sessionsaver/__init__.py
/usr/lib64/gedit/plugins/sessionsaver/appactivatable.py
/usr/lib64/gedit/plugins/sessionsaver/dialogs.py
/usr/lib64/gedit/plugins/sessionsaver/store/session.py
/usr/lib64/gedit/plugins/sessionsaver/store/sessionstore.py
/usr/lib64/gedit/plugins/sessionsaver/store/xmlsessionstore.py
/usr/lib64/gedit/plugins/sessionsaver/windowactivable.py
/usr/lib64/gedit/plugins/smartspaces.plugin
/usr/lib64/gedit/plugins/smartspaces.py
/usr/lib64/gedit/plugins/synctex.plugin
/usr/lib64/gedit/plugins/synctex/__init__.py
/usr/lib64/gedit/plugins/synctex/evince_dbus.py
/usr/lib64/gedit/plugins/synctex/synctex.py
/usr/lib64/gedit/plugins/terminal.plugin
/usr/lib64/gedit/plugins/terminal.py
/usr/lib64/gedit/plugins/textsize.plugin
/usr/lib64/gedit/plugins/textsize/__init__.py
/usr/lib64/gedit/plugins/textsize/signals.py
/usr/lib64/gedit/plugins/textsize/viewactivatable.py
/usr/lib64/gedit/plugins/translate.plugin
/usr/lib64/gedit/plugins/translate/__init__.py
/usr/lib64/gedit/plugins/translate/preferences.py
/usr/lib64/gedit/plugins/translate/services/apertium.py
/usr/lib64/gedit/plugins/translate/services/service.py
/usr/lib64/gedit/plugins/translate/services/services.py
/usr/lib64/gedit/plugins/translate/services/yandex.py
/usr/lib64/gedit/plugins/translate/settings.py
/usr/lib64/gedit/plugins/translate/translateview.py
/usr/lib64/gedit/plugins/wordcompletion.plugin

%files data
%defattr(-,root,root,-)
/usr/share/gedit/plugins/colorschemer/ui/schemer.ui
/usr/share/gedit/plugins/commander/modules/align.py
/usr/share/gedit/plugins/commander/modules/bookmark.py
/usr/share/gedit/plugins/commander/modules/doc.py
/usr/share/gedit/plugins/commander/modules/edit.py
/usr/share/gedit/plugins/commander/modules/find/__init__.py
/usr/share/gedit/plugins/commander/modules/find/finder.py
/usr/share/gedit/plugins/commander/modules/find/regex.py
/usr/share/gedit/plugins/commander/modules/format.py
/usr/share/gedit/plugins/commander/modules/goto.py
/usr/share/gedit/plugins/commander/modules/grep.py
/usr/share/gedit/plugins/commander/modules/help.py
/usr/share/gedit/plugins/commander/modules/move.py
/usr/share/gedit/plugins/commander/modules/reload.py
/usr/share/gedit/plugins/commander/modules/set.py
/usr/share/gedit/plugins/commander/modules/shell.py
/usr/share/gedit/plugins/sessionsaver/ui/sessionsaver.ui
/usr/share/gedit/plugins/translate/ui/preferences.ui
/usr/share/glib-2.0/schemas/org.gnome.gedit.plugins.drawspaces.gschema.xml
/usr/share/glib-2.0/schemas/org.gnome.gedit.plugins.terminal.gschema.xml
/usr/share/glib-2.0/schemas/org.gnome.gedit.plugins.translate.gschema.xml
/usr/share/glib-2.0/schemas/org.gnome.gedit.plugins.wordcompletion.gschema.xml
/usr/share/metainfo/gedit-bookmarks.metainfo.xml
/usr/share/metainfo/gedit-bracketcompletion.metainfo.xml
/usr/share/metainfo/gedit-charmap.metainfo.xml
/usr/share/metainfo/gedit-codecomment.metainfo.xml
/usr/share/metainfo/gedit-colorpicker.metainfo.xml
/usr/share/metainfo/gedit-colorschemer.metainfo.xml
/usr/share/metainfo/gedit-commander.metainfo.xml
/usr/share/metainfo/gedit-drawspaces.metainfo.xml
/usr/share/metainfo/gedit-findinfiles.metainfo.xml
/usr/share/metainfo/gedit-git.metainfo.xml
/usr/share/metainfo/gedit-joinlines.metainfo.xml
/usr/share/metainfo/gedit-multiedit.metainfo.xml
/usr/share/metainfo/gedit-smartspaces.metainfo.xml
/usr/share/metainfo/gedit-synctex.metainfo.xml
/usr/share/metainfo/gedit-terminal.metainfo.xml
/usr/share/metainfo/gedit-textsize.metainfo.xml
/usr/share/metainfo/gedit-translate.metainfo.xml
/usr/share/metainfo/gedit-wordcompletion.metainfo.xml

%files doc
%defattr(0644,root,root,0755)
/usr/share/help/C/gedit/bookmarks.page
/usr/share/help/C/gedit/bracket-comp.page
/usr/share/help/C/gedit/character-map.page
/usr/share/help/C/gedit/code-comment.page
/usr/share/help/C/gedit/color-picker.page
/usr/share/help/C/gedit/commander.page
/usr/share/help/C/gedit/draw-spaces.page
/usr/share/help/C/gedit/git.page
/usr/share/help/C/gedit/join-split-lines.page
/usr/share/help/C/gedit/legal-plugins.xml
/usr/share/help/C/gedit/multi-edit.page
/usr/share/help/C/gedit/session-saver.page
/usr/share/help/C/gedit/synctex.page
/usr/share/help/C/gedit/terminal.page
/usr/share/help/C/gedit/text-size.page
/usr/share/help/C/gedit/translate.page
/usr/share/help/C/gedit/word-completion.page
/usr/share/help/ar/gedit/bookmarks.page
/usr/share/help/ar/gedit/bracket-comp.page
/usr/share/help/ar/gedit/character-map.page
/usr/share/help/ar/gedit/code-comment.page
/usr/share/help/ar/gedit/color-picker.page
/usr/share/help/ar/gedit/commander.page
/usr/share/help/ar/gedit/draw-spaces.page
/usr/share/help/ar/gedit/git.page
/usr/share/help/ar/gedit/join-split-lines.page
/usr/share/help/ar/gedit/legal-plugins.xml
/usr/share/help/ar/gedit/multi-edit.page
/usr/share/help/ar/gedit/session-saver.page
/usr/share/help/ar/gedit/synctex.page
/usr/share/help/ar/gedit/terminal.page
/usr/share/help/ar/gedit/text-size.page
/usr/share/help/ar/gedit/translate.page
/usr/share/help/ar/gedit/word-completion.page
/usr/share/help/bg/gedit/bookmarks.page
/usr/share/help/bg/gedit/bracket-comp.page
/usr/share/help/bg/gedit/character-map.page
/usr/share/help/bg/gedit/code-comment.page
/usr/share/help/bg/gedit/color-picker.page
/usr/share/help/bg/gedit/commander.page
/usr/share/help/bg/gedit/draw-spaces.page
/usr/share/help/bg/gedit/git.page
/usr/share/help/bg/gedit/join-split-lines.page
/usr/share/help/bg/gedit/legal-plugins.xml
/usr/share/help/bg/gedit/multi-edit.page
/usr/share/help/bg/gedit/session-saver.page
/usr/share/help/bg/gedit/synctex.page
/usr/share/help/bg/gedit/terminal.page
/usr/share/help/bg/gedit/text-size.page
/usr/share/help/bg/gedit/translate.page
/usr/share/help/bg/gedit/word-completion.page
/usr/share/help/ca/gedit/bookmarks.page
/usr/share/help/ca/gedit/bracket-comp.page
/usr/share/help/ca/gedit/character-map.page
/usr/share/help/ca/gedit/code-comment.page
/usr/share/help/ca/gedit/color-picker.page
/usr/share/help/ca/gedit/commander.page
/usr/share/help/ca/gedit/draw-spaces.page
/usr/share/help/ca/gedit/git.page
/usr/share/help/ca/gedit/join-split-lines.page
/usr/share/help/ca/gedit/legal-plugins.xml
/usr/share/help/ca/gedit/multi-edit.page
/usr/share/help/ca/gedit/session-saver.page
/usr/share/help/ca/gedit/synctex.page
/usr/share/help/ca/gedit/terminal.page
/usr/share/help/ca/gedit/text-size.page
/usr/share/help/ca/gedit/translate.page
/usr/share/help/ca/gedit/word-completion.page
/usr/share/help/cs/gedit/bookmarks.page
/usr/share/help/cs/gedit/bracket-comp.page
/usr/share/help/cs/gedit/character-map.page
/usr/share/help/cs/gedit/code-comment.page
/usr/share/help/cs/gedit/color-picker.page
/usr/share/help/cs/gedit/commander.page
/usr/share/help/cs/gedit/draw-spaces.page
/usr/share/help/cs/gedit/git.page
/usr/share/help/cs/gedit/join-split-lines.page
/usr/share/help/cs/gedit/legal-plugins.xml
/usr/share/help/cs/gedit/multi-edit.page
/usr/share/help/cs/gedit/session-saver.page
/usr/share/help/cs/gedit/synctex.page
/usr/share/help/cs/gedit/terminal.page
/usr/share/help/cs/gedit/text-size.page
/usr/share/help/cs/gedit/translate.page
/usr/share/help/cs/gedit/word-completion.page
/usr/share/help/da/gedit/bookmarks.page
/usr/share/help/da/gedit/bracket-comp.page
/usr/share/help/da/gedit/character-map.page
/usr/share/help/da/gedit/code-comment.page
/usr/share/help/da/gedit/color-picker.page
/usr/share/help/da/gedit/commander.page
/usr/share/help/da/gedit/draw-spaces.page
/usr/share/help/da/gedit/git.page
/usr/share/help/da/gedit/join-split-lines.page
/usr/share/help/da/gedit/legal-plugins.xml
/usr/share/help/da/gedit/multi-edit.page
/usr/share/help/da/gedit/session-saver.page
/usr/share/help/da/gedit/synctex.page
/usr/share/help/da/gedit/terminal.page
/usr/share/help/da/gedit/text-size.page
/usr/share/help/da/gedit/translate.page
/usr/share/help/da/gedit/word-completion.page
/usr/share/help/de/gedit/bookmarks.page
/usr/share/help/de/gedit/bracket-comp.page
/usr/share/help/de/gedit/character-map.page
/usr/share/help/de/gedit/code-comment.page
/usr/share/help/de/gedit/color-picker.page
/usr/share/help/de/gedit/commander.page
/usr/share/help/de/gedit/draw-spaces.page
/usr/share/help/de/gedit/git.page
/usr/share/help/de/gedit/join-split-lines.page
/usr/share/help/de/gedit/legal-plugins.xml
/usr/share/help/de/gedit/multi-edit.page
/usr/share/help/de/gedit/session-saver.page
/usr/share/help/de/gedit/synctex.page
/usr/share/help/de/gedit/terminal.page
/usr/share/help/de/gedit/text-size.page
/usr/share/help/de/gedit/translate.page
/usr/share/help/de/gedit/word-completion.page
/usr/share/help/el/gedit/bookmarks.page
/usr/share/help/el/gedit/bracket-comp.page
/usr/share/help/el/gedit/character-map.page
/usr/share/help/el/gedit/code-comment.page
/usr/share/help/el/gedit/color-picker.page
/usr/share/help/el/gedit/commander.page
/usr/share/help/el/gedit/draw-spaces.page
/usr/share/help/el/gedit/git.page
/usr/share/help/el/gedit/join-split-lines.page
/usr/share/help/el/gedit/legal-plugins.xml
/usr/share/help/el/gedit/multi-edit.page
/usr/share/help/el/gedit/session-saver.page
/usr/share/help/el/gedit/synctex.page
/usr/share/help/el/gedit/terminal.page
/usr/share/help/el/gedit/text-size.page
/usr/share/help/el/gedit/translate.page
/usr/share/help/el/gedit/word-completion.page
/usr/share/help/es/gedit/bookmarks.page
/usr/share/help/es/gedit/bracket-comp.page
/usr/share/help/es/gedit/character-map.page
/usr/share/help/es/gedit/code-comment.page
/usr/share/help/es/gedit/color-picker.page
/usr/share/help/es/gedit/commander.page
/usr/share/help/es/gedit/draw-spaces.page
/usr/share/help/es/gedit/git.page
/usr/share/help/es/gedit/join-split-lines.page
/usr/share/help/es/gedit/legal-plugins.xml
/usr/share/help/es/gedit/multi-edit.page
/usr/share/help/es/gedit/session-saver.page
/usr/share/help/es/gedit/synctex.page
/usr/share/help/es/gedit/terminal.page
/usr/share/help/es/gedit/text-size.page
/usr/share/help/es/gedit/translate.page
/usr/share/help/es/gedit/word-completion.page
/usr/share/help/eu/gedit/bookmarks.page
/usr/share/help/eu/gedit/bracket-comp.page
/usr/share/help/eu/gedit/character-map.page
/usr/share/help/eu/gedit/code-comment.page
/usr/share/help/eu/gedit/color-picker.page
/usr/share/help/eu/gedit/commander.page
/usr/share/help/eu/gedit/draw-spaces.page
/usr/share/help/eu/gedit/git.page
/usr/share/help/eu/gedit/join-split-lines.page
/usr/share/help/eu/gedit/legal-plugins.xml
/usr/share/help/eu/gedit/multi-edit.page
/usr/share/help/eu/gedit/session-saver.page
/usr/share/help/eu/gedit/synctex.page
/usr/share/help/eu/gedit/terminal.page
/usr/share/help/eu/gedit/text-size.page
/usr/share/help/eu/gedit/translate.page
/usr/share/help/eu/gedit/word-completion.page
/usr/share/help/fi/gedit/bookmarks.page
/usr/share/help/fi/gedit/bracket-comp.page
/usr/share/help/fi/gedit/character-map.page
/usr/share/help/fi/gedit/code-comment.page
/usr/share/help/fi/gedit/color-picker.page
/usr/share/help/fi/gedit/commander.page
/usr/share/help/fi/gedit/draw-spaces.page
/usr/share/help/fi/gedit/git.page
/usr/share/help/fi/gedit/join-split-lines.page
/usr/share/help/fi/gedit/legal-plugins.xml
/usr/share/help/fi/gedit/multi-edit.page
/usr/share/help/fi/gedit/session-saver.page
/usr/share/help/fi/gedit/synctex.page
/usr/share/help/fi/gedit/terminal.page
/usr/share/help/fi/gedit/text-size.page
/usr/share/help/fi/gedit/translate.page
/usr/share/help/fi/gedit/word-completion.page
/usr/share/help/fr/gedit/bookmarks.page
/usr/share/help/fr/gedit/bracket-comp.page
/usr/share/help/fr/gedit/character-map.page
/usr/share/help/fr/gedit/code-comment.page
/usr/share/help/fr/gedit/color-picker.page
/usr/share/help/fr/gedit/commander.page
/usr/share/help/fr/gedit/draw-spaces.page
/usr/share/help/fr/gedit/git.page
/usr/share/help/fr/gedit/join-split-lines.page
/usr/share/help/fr/gedit/legal-plugins.xml
/usr/share/help/fr/gedit/multi-edit.page
/usr/share/help/fr/gedit/session-saver.page
/usr/share/help/fr/gedit/synctex.page
/usr/share/help/fr/gedit/terminal.page
/usr/share/help/fr/gedit/text-size.page
/usr/share/help/fr/gedit/translate.page
/usr/share/help/fr/gedit/word-completion.page
/usr/share/help/gl/gedit/bookmarks.page
/usr/share/help/gl/gedit/bracket-comp.page
/usr/share/help/gl/gedit/character-map.page
/usr/share/help/gl/gedit/code-comment.page
/usr/share/help/gl/gedit/color-picker.page
/usr/share/help/gl/gedit/commander.page
/usr/share/help/gl/gedit/draw-spaces.page
/usr/share/help/gl/gedit/git.page
/usr/share/help/gl/gedit/join-split-lines.page
/usr/share/help/gl/gedit/legal-plugins.xml
/usr/share/help/gl/gedit/multi-edit.page
/usr/share/help/gl/gedit/session-saver.page
/usr/share/help/gl/gedit/synctex.page
/usr/share/help/gl/gedit/terminal.page
/usr/share/help/gl/gedit/text-size.page
/usr/share/help/gl/gedit/translate.page
/usr/share/help/gl/gedit/word-completion.page
/usr/share/help/hu/gedit/bookmarks.page
/usr/share/help/hu/gedit/bracket-comp.page
/usr/share/help/hu/gedit/character-map.page
/usr/share/help/hu/gedit/code-comment.page
/usr/share/help/hu/gedit/color-picker.page
/usr/share/help/hu/gedit/commander.page
/usr/share/help/hu/gedit/draw-spaces.page
/usr/share/help/hu/gedit/git.page
/usr/share/help/hu/gedit/join-split-lines.page
/usr/share/help/hu/gedit/legal-plugins.xml
/usr/share/help/hu/gedit/multi-edit.page
/usr/share/help/hu/gedit/session-saver.page
/usr/share/help/hu/gedit/synctex.page
/usr/share/help/hu/gedit/terminal.page
/usr/share/help/hu/gedit/text-size.page
/usr/share/help/hu/gedit/translate.page
/usr/share/help/hu/gedit/word-completion.page
/usr/share/help/it/gedit/bookmarks.page
/usr/share/help/it/gedit/bracket-comp.page
/usr/share/help/it/gedit/character-map.page
/usr/share/help/it/gedit/code-comment.page
/usr/share/help/it/gedit/color-picker.page
/usr/share/help/it/gedit/commander.page
/usr/share/help/it/gedit/draw-spaces.page
/usr/share/help/it/gedit/git.page
/usr/share/help/it/gedit/join-split-lines.page
/usr/share/help/it/gedit/legal-plugins.xml
/usr/share/help/it/gedit/multi-edit.page
/usr/share/help/it/gedit/session-saver.page
/usr/share/help/it/gedit/synctex.page
/usr/share/help/it/gedit/terminal.page
/usr/share/help/it/gedit/text-size.page
/usr/share/help/it/gedit/translate.page
/usr/share/help/it/gedit/word-completion.page
/usr/share/help/ja/gedit/bookmarks.page
/usr/share/help/ja/gedit/bracket-comp.page
/usr/share/help/ja/gedit/character-map.page
/usr/share/help/ja/gedit/code-comment.page
/usr/share/help/ja/gedit/color-picker.page
/usr/share/help/ja/gedit/commander.page
/usr/share/help/ja/gedit/draw-spaces.page
/usr/share/help/ja/gedit/git.page
/usr/share/help/ja/gedit/join-split-lines.page
/usr/share/help/ja/gedit/legal-plugins.xml
/usr/share/help/ja/gedit/multi-edit.page
/usr/share/help/ja/gedit/session-saver.page
/usr/share/help/ja/gedit/synctex.page
/usr/share/help/ja/gedit/terminal.page
/usr/share/help/ja/gedit/text-size.page
/usr/share/help/ja/gedit/translate.page
/usr/share/help/ja/gedit/word-completion.page
/usr/share/help/ko/gedit/bookmarks.page
/usr/share/help/ko/gedit/bracket-comp.page
/usr/share/help/ko/gedit/character-map.page
/usr/share/help/ko/gedit/code-comment.page
/usr/share/help/ko/gedit/color-picker.page
/usr/share/help/ko/gedit/commander.page
/usr/share/help/ko/gedit/draw-spaces.page
/usr/share/help/ko/gedit/git.page
/usr/share/help/ko/gedit/join-split-lines.page
/usr/share/help/ko/gedit/legal-plugins.xml
/usr/share/help/ko/gedit/multi-edit.page
/usr/share/help/ko/gedit/session-saver.page
/usr/share/help/ko/gedit/synctex.page
/usr/share/help/ko/gedit/terminal.page
/usr/share/help/ko/gedit/text-size.page
/usr/share/help/ko/gedit/translate.page
/usr/share/help/ko/gedit/word-completion.page
/usr/share/help/lv/gedit/bookmarks.page
/usr/share/help/lv/gedit/bracket-comp.page
/usr/share/help/lv/gedit/character-map.page
/usr/share/help/lv/gedit/code-comment.page
/usr/share/help/lv/gedit/color-picker.page
/usr/share/help/lv/gedit/commander.page
/usr/share/help/lv/gedit/draw-spaces.page
/usr/share/help/lv/gedit/git.page
/usr/share/help/lv/gedit/join-split-lines.page
/usr/share/help/lv/gedit/legal-plugins.xml
/usr/share/help/lv/gedit/multi-edit.page
/usr/share/help/lv/gedit/session-saver.page
/usr/share/help/lv/gedit/synctex.page
/usr/share/help/lv/gedit/terminal.page
/usr/share/help/lv/gedit/text-size.page
/usr/share/help/lv/gedit/translate.page
/usr/share/help/lv/gedit/word-completion.page
/usr/share/help/oc/gedit/bookmarks.page
/usr/share/help/oc/gedit/bracket-comp.page
/usr/share/help/oc/gedit/character-map.page
/usr/share/help/oc/gedit/code-comment.page
/usr/share/help/oc/gedit/color-picker.page
/usr/share/help/oc/gedit/commander.page
/usr/share/help/oc/gedit/draw-spaces.page
/usr/share/help/oc/gedit/git.page
/usr/share/help/oc/gedit/join-split-lines.page
/usr/share/help/oc/gedit/legal-plugins.xml
/usr/share/help/oc/gedit/multi-edit.page
/usr/share/help/oc/gedit/session-saver.page
/usr/share/help/oc/gedit/synctex.page
/usr/share/help/oc/gedit/terminal.page
/usr/share/help/oc/gedit/text-size.page
/usr/share/help/oc/gedit/translate.page
/usr/share/help/oc/gedit/word-completion.page
/usr/share/help/pl/gedit/bookmarks.page
/usr/share/help/pl/gedit/bracket-comp.page
/usr/share/help/pl/gedit/character-map.page
/usr/share/help/pl/gedit/code-comment.page
/usr/share/help/pl/gedit/color-picker.page
/usr/share/help/pl/gedit/commander.page
/usr/share/help/pl/gedit/draw-spaces.page
/usr/share/help/pl/gedit/git.page
/usr/share/help/pl/gedit/join-split-lines.page
/usr/share/help/pl/gedit/legal-plugins.xml
/usr/share/help/pl/gedit/multi-edit.page
/usr/share/help/pl/gedit/session-saver.page
/usr/share/help/pl/gedit/synctex.page
/usr/share/help/pl/gedit/terminal.page
/usr/share/help/pl/gedit/text-size.page
/usr/share/help/pl/gedit/translate.page
/usr/share/help/pl/gedit/word-completion.page
/usr/share/help/pt_BR/gedit/bookmarks.page
/usr/share/help/pt_BR/gedit/bracket-comp.page
/usr/share/help/pt_BR/gedit/character-map.page
/usr/share/help/pt_BR/gedit/code-comment.page
/usr/share/help/pt_BR/gedit/color-picker.page
/usr/share/help/pt_BR/gedit/commander.page
/usr/share/help/pt_BR/gedit/draw-spaces.page
/usr/share/help/pt_BR/gedit/git.page
/usr/share/help/pt_BR/gedit/join-split-lines.page
/usr/share/help/pt_BR/gedit/legal-plugins.xml
/usr/share/help/pt_BR/gedit/multi-edit.page
/usr/share/help/pt_BR/gedit/session-saver.page
/usr/share/help/pt_BR/gedit/synctex.page
/usr/share/help/pt_BR/gedit/terminal.page
/usr/share/help/pt_BR/gedit/text-size.page
/usr/share/help/pt_BR/gedit/translate.page
/usr/share/help/pt_BR/gedit/word-completion.page
/usr/share/help/ru/gedit/bookmarks.page
/usr/share/help/ru/gedit/bracket-comp.page
/usr/share/help/ru/gedit/character-map.page
/usr/share/help/ru/gedit/code-comment.page
/usr/share/help/ru/gedit/color-picker.page
/usr/share/help/ru/gedit/commander.page
/usr/share/help/ru/gedit/draw-spaces.page
/usr/share/help/ru/gedit/git.page
/usr/share/help/ru/gedit/join-split-lines.page
/usr/share/help/ru/gedit/legal-plugins.xml
/usr/share/help/ru/gedit/multi-edit.page
/usr/share/help/ru/gedit/session-saver.page
/usr/share/help/ru/gedit/synctex.page
/usr/share/help/ru/gedit/terminal.page
/usr/share/help/ru/gedit/text-size.page
/usr/share/help/ru/gedit/translate.page
/usr/share/help/ru/gedit/word-completion.page
/usr/share/help/sl/gedit/bookmarks.page
/usr/share/help/sl/gedit/bracket-comp.page
/usr/share/help/sl/gedit/character-map.page
/usr/share/help/sl/gedit/code-comment.page
/usr/share/help/sl/gedit/color-picker.page
/usr/share/help/sl/gedit/commander.page
/usr/share/help/sl/gedit/draw-spaces.page
/usr/share/help/sl/gedit/git.page
/usr/share/help/sl/gedit/join-split-lines.page
/usr/share/help/sl/gedit/legal-plugins.xml
/usr/share/help/sl/gedit/multi-edit.page
/usr/share/help/sl/gedit/session-saver.page
/usr/share/help/sl/gedit/synctex.page
/usr/share/help/sl/gedit/terminal.page
/usr/share/help/sl/gedit/text-size.page
/usr/share/help/sl/gedit/translate.page
/usr/share/help/sl/gedit/word-completion.page
/usr/share/help/sv/gedit/bookmarks.page
/usr/share/help/sv/gedit/bracket-comp.page
/usr/share/help/sv/gedit/character-map.page
/usr/share/help/sv/gedit/code-comment.page
/usr/share/help/sv/gedit/color-picker.page
/usr/share/help/sv/gedit/commander.page
/usr/share/help/sv/gedit/draw-spaces.page
/usr/share/help/sv/gedit/git.page
/usr/share/help/sv/gedit/join-split-lines.page
/usr/share/help/sv/gedit/legal-plugins.xml
/usr/share/help/sv/gedit/multi-edit.page
/usr/share/help/sv/gedit/session-saver.page
/usr/share/help/sv/gedit/synctex.page
/usr/share/help/sv/gedit/terminal.page
/usr/share/help/sv/gedit/text-size.page
/usr/share/help/sv/gedit/translate.page
/usr/share/help/sv/gedit/word-completion.page
/usr/share/help/te/gedit/bookmarks.page
/usr/share/help/te/gedit/bracket-comp.page
/usr/share/help/te/gedit/character-map.page
/usr/share/help/te/gedit/code-comment.page
/usr/share/help/te/gedit/color-picker.page
/usr/share/help/te/gedit/commander.page
/usr/share/help/te/gedit/draw-spaces.page
/usr/share/help/te/gedit/git.page
/usr/share/help/te/gedit/join-split-lines.page
/usr/share/help/te/gedit/legal-plugins.xml
/usr/share/help/te/gedit/multi-edit.page
/usr/share/help/te/gedit/session-saver.page
/usr/share/help/te/gedit/synctex.page
/usr/share/help/te/gedit/terminal.page
/usr/share/help/te/gedit/text-size.page
/usr/share/help/te/gedit/translate.page
/usr/share/help/te/gedit/word-completion.page
/usr/share/help/th/gedit/bookmarks.page
/usr/share/help/th/gedit/bracket-comp.page
/usr/share/help/th/gedit/character-map.page
/usr/share/help/th/gedit/code-comment.page
/usr/share/help/th/gedit/color-picker.page
/usr/share/help/th/gedit/commander.page
/usr/share/help/th/gedit/draw-spaces.page
/usr/share/help/th/gedit/git.page
/usr/share/help/th/gedit/join-split-lines.page
/usr/share/help/th/gedit/legal-plugins.xml
/usr/share/help/th/gedit/multi-edit.page
/usr/share/help/th/gedit/session-saver.page
/usr/share/help/th/gedit/synctex.page
/usr/share/help/th/gedit/terminal.page
/usr/share/help/th/gedit/text-size.page
/usr/share/help/th/gedit/translate.page
/usr/share/help/th/gedit/word-completion.page
/usr/share/help/uk/gedit/bookmarks.page
/usr/share/help/uk/gedit/bracket-comp.page
/usr/share/help/uk/gedit/character-map.page
/usr/share/help/uk/gedit/code-comment.page
/usr/share/help/uk/gedit/color-picker.page
/usr/share/help/uk/gedit/commander.page
/usr/share/help/uk/gedit/draw-spaces.page
/usr/share/help/uk/gedit/git.page
/usr/share/help/uk/gedit/join-split-lines.page
/usr/share/help/uk/gedit/legal-plugins.xml
/usr/share/help/uk/gedit/multi-edit.page
/usr/share/help/uk/gedit/session-saver.page
/usr/share/help/uk/gedit/synctex.page
/usr/share/help/uk/gedit/terminal.page
/usr/share/help/uk/gedit/text-size.page
/usr/share/help/uk/gedit/translate.page
/usr/share/help/uk/gedit/word-completion.page
/usr/share/help/zh_CN/gedit/bookmarks.page
/usr/share/help/zh_CN/gedit/bracket-comp.page
/usr/share/help/zh_CN/gedit/character-map.page
/usr/share/help/zh_CN/gedit/code-comment.page
/usr/share/help/zh_CN/gedit/color-picker.page
/usr/share/help/zh_CN/gedit/commander.page
/usr/share/help/zh_CN/gedit/draw-spaces.page
/usr/share/help/zh_CN/gedit/git.page
/usr/share/help/zh_CN/gedit/join-split-lines.page
/usr/share/help/zh_CN/gedit/legal-plugins.xml
/usr/share/help/zh_CN/gedit/multi-edit.page
/usr/share/help/zh_CN/gedit/session-saver.page
/usr/share/help/zh_CN/gedit/synctex.page
/usr/share/help/zh_CN/gedit/terminal.page
/usr/share/help/zh_CN/gedit/text-size.page
/usr/share/help/zh_CN/gedit/translate.page
/usr/share/help/zh_CN/gedit/word-completion.page
/usr/share/help/zh_HK/gedit/bookmarks.page
/usr/share/help/zh_HK/gedit/bracket-comp.page
/usr/share/help/zh_HK/gedit/character-map.page
/usr/share/help/zh_HK/gedit/code-comment.page
/usr/share/help/zh_HK/gedit/color-picker.page
/usr/share/help/zh_HK/gedit/commander.page
/usr/share/help/zh_HK/gedit/draw-spaces.page
/usr/share/help/zh_HK/gedit/git.page
/usr/share/help/zh_HK/gedit/join-split-lines.page
/usr/share/help/zh_HK/gedit/legal-plugins.xml
/usr/share/help/zh_HK/gedit/multi-edit.page
/usr/share/help/zh_HK/gedit/session-saver.page
/usr/share/help/zh_HK/gedit/synctex.page
/usr/share/help/zh_HK/gedit/terminal.page
/usr/share/help/zh_HK/gedit/text-size.page
/usr/share/help/zh_HK/gedit/translate.page
/usr/share/help/zh_HK/gedit/word-completion.page
/usr/share/help/zh_TW/gedit/bookmarks.page
/usr/share/help/zh_TW/gedit/bracket-comp.page
/usr/share/help/zh_TW/gedit/character-map.page
/usr/share/help/zh_TW/gedit/code-comment.page
/usr/share/help/zh_TW/gedit/color-picker.page
/usr/share/help/zh_TW/gedit/commander.page
/usr/share/help/zh_TW/gedit/draw-spaces.page
/usr/share/help/zh_TW/gedit/git.page
/usr/share/help/zh_TW/gedit/join-split-lines.page
/usr/share/help/zh_TW/gedit/legal-plugins.xml
/usr/share/help/zh_TW/gedit/multi-edit.page
/usr/share/help/zh_TW/gedit/session-saver.page
/usr/share/help/zh_TW/gedit/synctex.page
/usr/share/help/zh_TW/gedit/terminal.page
/usr/share/help/zh_TW/gedit/text-size.page
/usr/share/help/zh_TW/gedit/translate.page
/usr/share/help/zh_TW/gedit/word-completion.page

%files lib
%defattr(-,root,root,-)
/usr/lib64/gedit/plugins/libbookmarks.so
/usr/lib64/gedit/plugins/libdrawspaces.so
/usr/lib64/gedit/plugins/libfindinfiles.so
/usr/lib64/gedit/plugins/libwordcompletion.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gedit-plugins-gnome/68c94ffc34f8ad2d7bfae3f5a6b996409211c1b1

%files locales -f gedit-plugins.lang
%defattr(-,root,root,-)

